language: julia
julia:
  - 1.3.1
  - 1.4.1
  - 1.5.0

codecov: true

after_success:
  - julia -e 'cd(Pkg.dir("RadiativeTransfer")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'